/**:
  ros__parameters:
    #wheel_radius: 0.383 # The radius of the wheel, primarily used for dead reckoning.
    #wheel_width: 0.235 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_radius: 0.153
    wheel_width: 0.135
    #wheel_base: 2.79 # between front wheel center and rear wheel center
    wheel_base: 1.6
    #wheel_tread: 1.64 # between left wheel center and right wheel center
    wheel_tread: 0.9
    #front_overhang: 1.0 # between front wheel center and vehicle front
    front_overhang: 0.6
    #rear_overhang: 1.1 # between rear wheel center and vehicle rear
    rear_overhang: 0.6
    #left_overhang: 0.128 # between left wheel center and vehicle left
    #right_overhang: 0.128 # between right wheel center and vehicle right
    left_overhang: 0.15
    right_overhang: 0.15
    #vehicle_height: 2.5
    vehicle_height: 1.8
    max_steer_angle: 0.70 # [rad]
